#
# Run repoman via travis
# See https://github.com/mrueg/repoman-travis
#
language: python
python:
    - "3.8"
env:
    - PORTAGE_VER="3.0.13"
before_install:
    - sudo apt-get -qq update
    - pip install lxml pyyaml
before_script:
    - lscpu
